###
POST https://apiminismart-production.up.railway.app/api/auth/login
Content-Type: application/json

{
    "email": "vietkhang04@gmail.com",
    "password": "112233"
}

###
GET http://localhost:3000/api/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThiZGMyMDQ1NzdlMmJkMGI2YmFiMTciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzY5NjMyNTYsImV4cCI6MTYzNjk3MDQ1Nn0.EXRl8rSQnKuyB4Ev1lDe6aYtJq8MYmOTThenSbs7RIQ


{
    "email": "vietkhang04@gmail.com",
    "password": "112233"
}