###
POST https://apiminismart-production.up.railway.app/api/auth/register
Content-Type: application/json

{
    "name": "khang",
    "surname": "takhang",
    "email": "vietkhang1024@gmail.com",
    "password": "112233"
}
